# Generated by Django 5.0.6 on 2024-07-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_faq_privacypolicy_termsandconditions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'السؤال الشائع', 'verbose_name_plural': 'الأسئلة الشائعة'},
        ),
        migrations.AlterModelOptions(
            name='termsandconditions',
            options={'verbose_name': 'الشروط والأحكام', 'verbose_name_plural': 'الشروط والأحكام'},
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(verbose_name='الإجابة'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=512, verbose_name='السؤال'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='content',
            field=models.TextField(verbose_name='المحتوى'),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='title',
            field=models.CharField(max_length=512, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='termsandconditions',
            name='content',
            field=models.TextField(verbose_name='المحتوى'),
        ),
        migrations.AlterField(
            model_name='termsandconditions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='termsandconditions',
            name='title',
            field=models.CharField(max_length=512, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='termsandconditions',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
    ]
