# Generated by Django 4.2 on 2024-08-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_brokerrequest_created_at_brokerrequest_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokerrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='brokerrequest',
            name='expected_transaction_amounts_per_month',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبالغ المتوقعة للمعاملات شهريًا'),
        ),
        migrations.AlterField(
            model_name='brokerrequest',
            name='mobile_number',
            field=models.CharField(max_length=15, unique=True, verbose_name='رقم الجوال'),
        ),
        migrations.AlterField(
            model_name='brokerrequest',
            name='name',
            field=models.CharField(max_length=255, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='brokerrequest',
            name='region',
            field=models.CharField(max_length=255, verbose_name='المنطقة'),
        ),
        migrations.AlterField(
            model_name='brokerrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='brokerrequest',
            name='years_of_experience',
            field=models.PositiveIntegerField(verbose_name='سنوات الخبرة'),
        ),
    ]
